//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.30 at 02:31:13 AM IST 
//


package za.co.discovery.assignment.rest;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the za.co.discovery.assignment.rest package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _RouteRequest_QNAME = new QName("http://www.example.org/find-shortest-route", "RouteRequest");
    private final static QName _RouteResponse_QNAME = new QName("http://www.example.org/find-shortest-route", "RouteResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: za.co.discovery.assignment.rest
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RouteRequestType }
     * 
     */
    public RouteRequestType createRouteRequestType() {
        return new RouteRequestType();
    }

    /**
     * Create an instance of {@link RouteResponseType }
     * 
     */
    public RouteResponseType createRouteResponseType() {
        return new RouteResponseType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RouteRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/find-shortest-route", name = "RouteRequest")
    public JAXBElement<RouteRequestType> createRouteRequest(RouteRequestType value) {
        return new JAXBElement<RouteRequestType>(_RouteRequest_QNAME, RouteRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RouteResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/find-shortest-route", name = "RouteResponse")
    public JAXBElement<RouteResponseType> createRouteResponse(RouteResponseType value) {
        return new JAXBElement<RouteResponseType>(_RouteResponse_QNAME, RouteResponseType.class, null, value);
    }

}
